# See https://github.com/marketplace/actions/close-stale-issues
# As used here, "stale" is a misnomer. This uses the predefined action close-stale-issues to
# label issues that have not been categorized with one of the triage label types
# shown in line 22. Runs on the 1st day of every month.
  
name: label-untriaged-issues

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Automatically marked uncategorized issue as product feedback'
          stale-issue-label: 'product-feedback'
          exempt-issue-labels: 'doc-bug,feature-request,doc-enhancement,doc-idea,doc-experience,product-issue,product-question'
          days-before-issue-stale: 1
